language: generic
os:
  - linux
arch: arm64

jobs:
  include:
    ########## DEVELOPER INSTALL ##########

    - &default
      env: DESC="browser test"
      before_install:
        - sudo apt-get install -y chromium-browser
        - export CHROME_BIN=/usr/bin/chromium-browser
        - sudo apt install software-properties-common
        - sudo add-apt-repository ppa:deadsnakes/ppa
        - sudo apt install python3.7
        - python3.7 --version
      install:
        - python -m pip install -e .
        - npm install
        - npm run build
      script: python -m jupyterlab.browser_check
