language: python
os:
  - linux
arch: arm64

jobs:
  include:
    ########## DEVELOPER INSTALL ##########

    - &default
      env: DESC="browser test"
      before_install:
        - wget https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-arm64.tar.gz
        - tar -xf node-v12.16.1-linux-arm64.tar.gz -C $HOME
        - export PATH=$HOME/node-v12.16.1-linux-arm64/bin:$PATH
        - echo $PATH
        - node -v
        - sudo apt-get install -y chromium-browser
        - export CHROME_BIN=/usr/bin/chromium-browser
      install:
        - python -m pip install -e .
        - npm install
        - npm run build
        - pip install --pre jupyterlab
      script: python -m jupyterlab.browser_check
