language: python
os:
  - linux
arch: arm64

jobs:
  include:
    ########## DEVELOPER INSTALL ##########

    - &default
      env: DESC="browser test"
      before_install:
        - sudo apt-get install -y chromium-browser
        - export CHROME_BIN=/usr/bin/chromium-browser
      install:
        - python -m pip install -e .
        - npm install
        - npm run build
      script: python -m jupyterlab.browser_check
